[build]
    publish = "public/"

[functions]
    directory = "functions"

[[redirects]]
    from = "/cors/beat-savior/*"
    to = "https://www.beatsavior.io/api/livescores/player/:splat"
    status = 200
    force = true
    headers = {X-From = "Netlify"}

[[redirects]]
    from = "/cors/score-saber/*"
    to = "https://www.scoresaber.com/:splat"
    status = 200
    force = true
    headers = {X-From = "Netlify"}
